export type SportCategory =
  | "Athlétisme"
  | "Sport collectif"
  | "Sport aquatique"
  | "Gymnastique"
  | "Sport de combat"
  | "Sport de raquette"
  | "Sport équestre"
  | "Sport urbain"
  | "Sport nautique"
  | "Cérémonie"
  | "Sport de force"
  | "Sport combiné"
  | "Golf"
  | "Cyclisme"
  | "Sport de précision"
