export const ERROR_KEYS = [
  "userNotFound",
  "emailAlreadyUsed",
  "wrongPassword",
  "cartNotActive",
  "cartExpired",
  "cartAlreadyPaid",
  "cartEmpty",
  "itemNotFound",
  "eventNotFound",
  "eventSoldOut",
  "eventAlreadyExists",
  "offerNotFound",
  "offerAlreadyExists",
  "cardDeclined",
  "insufficientFunds",
  "cardExpired",
  "transactionNotFound",
  "noValidTickets",
  "invalidOtpCode",
  "otpExpired",
  "otpMaxAttempts",
  "invalidCredentials",
  "invalidEmail",
  "passwordMin",
  "passwordUppercase",
  "passwordDigit",
  "passwordsMustMatch",
  "currentPasswordRequired",
  "firstNameMin",
  "firstNameMax",
  "lastNameMin",
  "lastNameMax",
  "termsRequired",
  "cardHolderMin",
  "cardNumberLength",
  "expiryFormat",
  "expiryMonth",
  "cvvFormat",
  "genericError",
  "networkError",
  "sessionExpired",
] as const

export type ErrorKey = (typeof ERROR_KEYS)[number]
